query usedOffers(
  $site_id: Int!,
  $page: Int!,
  $limit: Int!,
  $mark_slug: String,
  $folder_slug: String,
  $sort: String,
  $generation_slug: String,
  $gearbox_id: Int,
  $body_type_id: Int,
  $drive_type_id: Int,
  $owner_id: Int,
  $price_from: Int,
  $price_to: Int,
  $year_from: Int,
  $year_to: Int
) {
  offers(
    page: $page,
    limit: $limit,
    site_id: $site_id,
    mark_slug: $mark_slug,
    folder_slug: $folder_slug,
    sort: $sort,
    generation_slug:$generation_slug,
    gearbox_id: $gearbox_id,
    body_type_id: $body_type_id,
    drive_type_id: $drive_type_id,
    owner_id: $owner_id,
    price_from: $price_from,
    price_to: $price_to,
    year_from: $year_from,
    year_to: $year_to
  ) {
    data {
      id
      name
      price
      price_old
      run
      year
      engine_power
      engine_volume
      mark {
        id
        slug
      }
      folder {
        id
        slug
      }
      images {
        thumb
      }
      owner {
        id
        title
        number
      }
      gearbox {
        id
        title
        name
      }
      engineType {
        id
        title
        name
      }
      external_id
      external_unique_id
      generation {
        id
        slug
        name
      }
    }
    last_page
  }
}
